#!/usr/bin/env node

var fs = require('fs');
var uglifyjs = require('uglify-js');

function shouldRemove(el) {
  if (el[0] === 'stat' && shouldRemove(el[1])) return true;
  if (el[0] === 'defun' && el[1] === 'debug') return true;
  if (el[0] === 'call' && el[1][0] === 'name' && el[1][1] === 'debug') return true;

  return false;
}

var mangleDebug = exports.mangleDebug = function mangleDebug(ast) {
  if (!Array.isArray(ast)) return ast;

  var out = [];

  ast.forEach(function(el) {
    if (!Array.isArray(el)) return out.push(el);
    if (shouldRemove(el)) return;

    out.push(mangleDebug(el));
  });

  return out;
}

var getAst = exports.getAst = function getAst(fname) {
  var code = fs.readFileSync(fname, 'utf-8');
  return uglifyjs.parser.parse(code);
}

function main() {
  var fname = process.argv[2];

  var ast = mangleDebug(getAst(fname));
  process.stdout.write(uglifyjs.uglify.gen_code(ast));
}

main();
